[package]
name = "plerkle_shim_dummy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
plerkle_shim = { path = "../plerkle_shim" }
solana-geyser-plugin-interface = { version = "1.11.3" }
